### ISSUE TITLE
Branch와 Fork 중 사용 정책 확정

### ISSUE THREAD

**Issue by kjw0412c** [capstone1802-AplusStory/FixMe#9]
피드백 : Fork 사용의 번거로움과 Branch 역시  백업가능

해당 피드백에 대해 Fork 사용의 타당성을 보이거나, Branch 사용으로 정책 변경하여 적용해야 함.

**Comment by plainswalker** [comment]
branch 관리 정책 변경 : 
 * master, (personel)/unstable, (personel)/workspace로 나뉨
 * master : stable codes
 * 각 인원마다 unstable과 workspace를 가짐
 * (personel)/unstable : does work, but not confirmed
 * (personel)/workspace : do anything you want
 * 다른 브랜치 만들지 말것
 * 다른 브랜치 필요하면 fork로 가져간 곳에서 작업하고, 자신의 workspace나 unstable브랜치로 PR 보낼것
